export {default as Hero} from "./hero/Hero"
export {default as Contact} from "./contact/Contact"
export {default as Parallax} from "./parallax/Parallax"
export {default as Education} from "./education/Education"
export {default as Portfolio} from "./portfolio/Portfolio"